### ISSUE TITLE
get the .jar file

### ISSUE THREAD

**Issue by Roy-NJU** [ucla-pls/wiretap#3]
Hi:
    Where can I download the .jar file？
 

Thanks!

**Comment by kalhauge** [comment]
Hi Roy, 

Great to see your interest in the project. 

Currently you have to build the jar file yourself. I can see that we are missing some information in the  You should be able to do this by cloning the repository and then running `ant jar`, given that you have java and ant installed.

**Comment by Roy-NJU** [comment]
Hi kalhauge :
     When I build the jar file,  an error ocurs " Build path entry is missing: Wiretap/lib/asm-5.1/output/build/tmp". Then I remove this lib, another error occurs " Could not write file: E:\source code of program analysis tools\wiretap\wiretap-master\build." How can I solve this problem.

**Comment by kalhauge** [comment]
Oh sorry, you have to run ant from the `lib/asm-5.1`, before as even though we use asm-5.1 as a library we needed to make some modification to it. After you have build asm-5.1 you should be able to build wiretap.

**Comment by Roy-NJU** [comment]
After I build asm-5.1, it generates a new directory"build", the asm-5.1.jar should be added into which directory? "build" or "lib". When I remove   "Wiretap/lib/asm-5.1/output/build/tmp" on the build path, compile errors occur under several files under src directory.

**Comment by kalhauge** [comment]
I have tried to download the repository from scratch, and these commands seem to work.
```
> git clone https://github.com/ucla-pls/wiretap.git
> cd wiretap
> ant
```
produces a jar file in `build/wiretap.jar`.

**Comment by Roy-NJU** [comment]
Hi:
   Thanks, I got wiretap.jar following your steps. But when I perform to instrument, exception happens:
============================================================
RecorderName edu.ucla.pls.wiretap.recorders.null
Could not find class 'edu.ucla.pls.wiretap.recorders.null'
java.lang.ClassNotFoundException: edu/ucla/pls/wiretap/recorders/null
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at edu.ucla.pls.wiretap.WiretapProperties.getRecorder(WiretapProperties.java:181)
	at edu.ucla.pls.wiretap.Agent.<init>(Agent.java:47)
	at edu.ucla.pls.wiretap.Agent.fromOptions(Agent.java:277)
	at edu.ucla.pls.wiretap.Agent.premain(Agent.java:289)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)
============================================================

Thanks!

**Comment by Roy-NJU** [comment]
Hi:
Thanks, I got wiretap.jar following your steps. But when I perform to instrument, exception happens:

RecorderName edu.ucla.pls.wiretap.recorders.null
Could not find class 'edu.ucla.pls.wiretap.recorders.null'
java.lang.ClassNotFoundException: edu/ucla/pls/wiretap/recorders/null
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Unknown Source)
at edu.ucla.pls.wiretap.WiretapProperties.getRecorder(WiretapProperties.java:181)
at edu.ucla.pls.wiretap.Agent.(Agent.java:47)
at edu.ucla.pls.wiretap.Agent.fromOptions(Agent.java:277)
at edu.ucla.pls.wiretap.Agent.premain(Agent.java:289)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)

Thanks!

**Comment by kalhauge** [comment]
This happens because you have to choose a reocrder. Choose one from the recorders in 'edu.ucla.pls.wiretap.recorders'  usign the '-Dwiretap.recorder=<recorder>' option, all the options are declared in https://github.com/ucla-pls/wiretap/blob/master/src/edu/ucla/pls/wiretap/WiretapProperties.java
