### ISSUE TITLE
Error running Dacapo benchmark "h2"

### ISSUE THREAD

**Issue by umangm** [ucla-pls/wiretap#5]
The version of Dacapo benchmark I am using has been downloaded from https://sourceforge.net/projects/dacapobench/files/9.12-bach-MR1/

My java version is 
```
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```

Command to reproduce:
```
java -javaagent:/path/to/wiretap.jar -Dwiretap.recorder=BinaryHistoryLogger -Dwiretap.classfilesfolder=_wiretap/classes    -Dwiretap.ignoredprefixes="org/mockito,org/powermock,edu/ucla/pls/wiretap,java,sun,org/dacapo/harness/" -jar /path/to/dacapo-9.12-MR1-bach.jar h2 -s small
```

Error encountered:
```
objc[50981]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/bin/java (0x10f08c4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10f1424e0). One of the two will be used. Which one is undefined.
RecorderName edu.ucla.pls.wiretap.recorders.BinaryHistoryLogger
Deadlock detector started!
WARNING: edu.ucla.pls.wiretap.wiretaps.ExitMethod@4aa298b7 not active: java.lang.NoSuchMethodException: edu.ucla.pls.wiretap.recorders.BinaryHistoryLogger.exit(int)
WARNING: edu.ucla.pls.wiretap.wiretaps.YieldObject@7d4991ad not active: java.lang.NoSuchMethodException: edu.ucla.pls.wiretap.recorders.BinaryHistoryLogger.yield(java.lang.Object, int)
WARNING: edu.ucla.pls.wiretap.wiretaps.ReturnMethod@28d93b30 not active: java.lang.NoSuchMethodException: edu.ucla.pls.wiretap.recorders.BinaryHistoryLogger.returnMethod(java.lang.Object, java.lang.String)
WARN: UNVERIFIED java/lang/System.out:Ljava/io/PrintStream;
Using scaled threading model. 4 processors detected, 4 threads used to drive the workload, in a possible range of [1,400]
WARNING: Assumes that java/lang/Thread is inheriting from thread.
WARNING: Assumes that java/lang/Thread is inheriting from thread.
java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:192)
	at org.dacapo.harness.TestHarness.main(TestHarness.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at Harness.main(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.dacapo.harness.H2.prepare(H2.java:64)
	at org.dacapo.harness.Benchmark.initialize(Benchmark.java:238)
	at org.dacapo.harness.Benchmark.<init>(Benchmark.java:217)
	at org.dacapo.harness.H2.<init>(H2.java:39)
	... 11 more
Caused by: java.lang.VerifyError: Expecting a stackmap frame at branch target 66
Exception Details:
  Location:
    org/dacapo/h2/TPCCReporter.reset()V @22: aload_0
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2a59 59b8 0024 594c 5f12 37b6 003a c22b
    0x0000010: 5f12 37b6 003d 2a2b 5f12 3eb6 0029 2a03
    0x0000020: 5a2b 5fb6 002d 5a2b 5f12 2e12 3fb6 0033
    0x0000030: b500 022b b600 362a 592b 5f12 40b6 0043
    0x0000040: c3b1 2a59 2b5f 1240 b600 43c3 c000 45bf
    0x0000050:                                        
  Exception Handler Table:
    bci [22, 66] => handler: 66

	at org.dacapo.h2.TPCC.<init>(Unknown Source)
	at org.dacapo.h2.TPCC.make(Unknown Source)
	... 19 more
Waiting for the main thread to close... 2s
Checking for deadlocks
Checking for deadlocks
Closing agent
Closing loggers...
- Closing Logger_0... Done.
Done closing loggers...
- Closing the global writer... Done.
- Closing class writer... Done.
- Closing field writer... Done.
- Closing method writer... Done.
- Closing instruction writer... Done.
Agent closed... Halting system.
```

**Comment by kalhauge** [comment]
Thanks for the bug report.  I think it is a problem with the current stack map implementation in ASM. So this bug won't' be fixed before we upgrade to a newer version of ASM. 

There is, however, an easy "fix". Run java in -noverify mode:

```
java -noverify -javaagent:/path/to/wiretap.jar -Dwiretap.recorder=BinaryHistoryLogger -Dwiretap.classfilesfolder=_wiretap/classes    -Dwiretap.ignoredprefixes="org/mockito,org/powermock,edu/ucla/pls/wiretap,java,sun,org/dacapo/harness/" -jar /path/to/dacapo-9.12-MR1-bach.jar h2 -s small
```

**Comment by umangm** [comment]
This fix worked for me. Please close the ticket.
